modLoader = "javafml" #mandatory
loaderVersion = "[4.10,)" #mandatory
license = "GPL3"
[[mods]] #mandatory
modId = "rdi" #mandatory
version = "4R" #mandatory
displayName = "RDI" #mandatory
authors = "calebxzhou" #optional
description = '''core mod for RDI modpack.
https://github.com/calebxzhou/rdi4
'''
[[mixins]]
config = "rdi.mixins.json"